# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8
  username: root
  password: p123
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_development

production:
  <<: *default
  database: bookstore_development
